name: 'Backup MongoDB'

on:
  push:
    branches:
      - '**'
#   schedule:
#     - cron: '0 2 * * *'

jobs:
  mongodump:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v3'

      - name: Set up MongoDB Database Tools
        run: |
          # Import the MongoDB public GPG key
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo tee /usr/share/keyrings/mongodb-server-6.0.gpg > /dev/null

          # Add the MongoDB repository
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

          # Update the package list
          sudo apt-get update

          # Install MongoDB Database Tools
          sudo apt-get install -y mongodb-database-tools

      - name: Verify mongodump Installation
        run: |
          mongodump --version
      # - name: 'Checkout repository'
      #   uses: 'actions/checkout@v3'

      # - name: Set up MongoDB Tools
      #   run: |
      #     sudo apt-get update
      #     sudo apt install ./mongodb-database-tools-*-100.10.0.deb

      # - name: Perform mongodump
      #   env:
      #     MONGO_URI: ${{ secrets.MONGO_URI }} # Use GitHub secrets to securely store connection string
      #   run: |
      #     mongodump --uri=$MONGO_URI --archive=dump-$(date +%F).gz --gzip
      #     find . -name "dump*.gz" -exec echo "Found dump file: {}" \;
