name: 'Backup MongoDB'

on:
  push:
    branches:
      - '**'
#   schedule:
#     - cron: '0 2 * * *'

jobs:
  mongodump:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v3'

      - name: Set up MongoDB Database Tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.7.2.deb
          sudo dpkg -i mongodb-database-tools-ubuntu2204-x86_64-100.7.2.deb
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools

      - name: Verify mongodump Installation
        run: |
          mongodump --version
      # - name: 'Checkout repository'
      #   uses: 'actions/checkout@v3'

      # - name: Set up MongoDB Tools
      #   run: |
      #     sudo apt-get update
      #     sudo apt install ./mongodb-database-tools-*-100.10.0.deb

      # - name: Perform mongodump
      #   env:
      #     MONGO_URI: ${{ secrets.MONGO_URI }} # Use GitHub secrets to securely store connection string
      #   run: |
      #     mongodump --uri=$MONGO_URI --archive=dump-$(date +%F).gz --gzip
      #     find . -name "dump*.gz" -exec echo "Found dump file: {}" \;
