name: Test

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches:
      - "test/workflow"

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo 'Test'
